### ISSUE TITLE
Dropdown height

### ISSUE THREAD

**Issue by jeffreyguo87** [jaredrummler/Material-Spinner#11]
Hello, can you please add a dropdown max dropdown height? I have too much items in the spinner and it goes all the way down to the screen. Thanks!

**Comment by jaredrummler** [comment]
Can you please provide a screenshot?

The View shows a PopupWindow when clicked and I have limited control over the max height of a PopupWindow.

**Comment by jeffreyguo87** [comment]
![1](https://cloud.githubusercontent.com/assets/16681690/15171949/5efdd824-1707-11e6-9bc6-e2e597c0e33d.png)

As you can see the popup window is all the way down to the screen, is there a way to leave some space between the bottom of the screen and the popup window? 

Thanks!

**Comment by jaredrummler** [comment]
You can now set the dropdown height or max height in 1.0.8.

**Example:**

In XML:

```xml
app:ms_dropdown_max_height="350dp"
app:ms_dropdown_height="wrap_content"
```

or Java:

```java
spinner.setDropdownHeight(WindowManager.LayoutParams.WRAP_CONTENT);
spinner.setDropdownMaxHeight(getResources().getDimension(R.dimen.spinner_max_height));
```

___

I'll close this, but if you find problems leave a comment.
