### ISSUE TITLE
Selecting the first item programmatically

### ISSUE THREAD

**Issue by jeffreyguo87** [jaredrummler/Material-Spinner#12]
How do you select the first item in the spinner?

I tried doing the following,

spinner.setOnItemListeners(..){ ... };

spinner.setSelectedIndex(2);
spinner.setSelected(true);

but it doesn't seem to be working.

Thanks!

**Comment by jaredrummler** [comment]
`spinner.setSelectedIndex(int)` should select that item. Make sure you invoke this method after setting the items in the spinner. For example, if I set the selected index to 1 in the sample, then "Jelly Bean" would be selected instead of "Ice Cream Sandwich".

```java
MaterialSpinner spinner = (MaterialSpinner) findViewById(R.id.spinner);
spinner.setItems("Ice Cream Sandwich", "Jelly Bean", "KitKat", "Lollipop", "Marshmallow");
spinner.setSelectedIndex(1); // <--- Set the item programmatically
spinner.setOnItemSelectedListener(new MaterialSpinner.OnItemSelectedListener<String>() {

  @Override public void onItemSelected(MaterialSpinner view, int position, long id, String item) {
    Snackbar.make(view, "Clicked " + item, Snackbar.LENGTH_LONG).show();
  }
});
spinner.setOnNothingSelectedListener(new MaterialSpinner.OnNothingSelectedListener() {

  @Override public void onNothingSelected(MaterialSpinner spinner) {
    Snackbar.make(spinner, "Nothing selected", Snackbar.LENGTH_LONG).show();
  }
});
```

**Comment by jeffreyguo87** [comment]
The method setSelectedIndex just chooses the item as the first item, but I would like to actually select the item as if it would call on onItemSelected.

Thanks again.

**Comment by jaredrummler** [comment]
You should just run whatever code is in your listener when you select the item. I don't know why this would be needed. If you really feel like this is necessary please provide an example.

**Comment by sunreview** [comment]
what he means is that when he use `spinner.setSelectedIndex(1);`,it justchoose the item to appear as the first item,but it didn't execute the selected event.
I have the same problem,please fix that to make this project better.Thanks man.very nice Spinner!

**Comment by ismail0234** [comment]
+1
