### ISSUE TITLE
get item by index number

### ISSUE THREAD

**Issue by iceberg1369** [jaredrummler/Material-Spinner#15]
Hi there 
let's assume I have following code:

        spinner = (MaterialSpinner) findViewById(R.id.spinner);
        spinner.setItems("Canada", "Germany", "France", "Netherlands", "United Kingdom", "United States");

how can I get items by index number?

**Comment by jaredrummler** [comment]
Do you want the selected item or do you want to get the item by position?

**Selected item:**

    String[] COUNTRIES = {"Canada", "Germany", "France", "Netherlands", "United Kingdom", "United States"};
    ...
    spinner.setItems(COUNTRIES);
    ...
    String selectedCounty = COUNTRIES[spinner.getSelectedIndex()];
____
**Item by index:**

    String[] COUNTRIES = {"Canada", "Germany", "France", "Netherlands", "United Kingdom", "United States"};
    ...
    spinner.setItems(COUNTRIES);
    ...
    String us = COUNTRIES[5];
____

I will add a method to get the current items.

**Comment by iceberg1369** [comment]
thanks you sir

**Comment by cazador4** [comment]
Have you added getCurrentItems?
I need something similar to [getSelectedItem() ](https://developer.android.com/reference/android/widget/AdapterView.html#getSelectedItem())

**Comment by cazador4** [comment]
thnx man! You are fast like chuck norris

**Comment by AceStan** [comment]
I don't understand how can i get the position of the current selected item ? :/
