### ISSUE TITLE
Hello sorry set height simple ? 

### ISSUE THREAD

**Issue by ooKriangsaKoo** [jaredrummler/Material-Spinner#16]
set position list The height of the show, all three.
Device : OS 6.0 marshmallow
_______________________
sorry language English of i
thank

![device-2559-07-04-140117](https://cloud.githubusercontent.com/assets/9163892/16553064/215e5d18-41f0-11e6-8742-df357be7b9e6.png)

**Comment by jaredrummler** [comment]
try changing/adding `app: ms_dropdown_max_height="<enter max height>"` and `app:ms_dropdown_height="<enter height>"`.

**Comment by ooKriangsaKoo** [comment]
` <com.jaredrummler.materialspinner.MaterialSpinner
                android:id="@+id/contactTypeSpinner"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:textColor="@color/genre"
                app:ms_background_color="#EEE"
                app:ms_dropdown_height="200dp"
                app:ms_dropdown_max_height="300dp"/>`

not work 
 `app: ms_dropdown_max_height="<enter max height>"`  and  `app:ms_dropdown_height="<enter height>" .`
