### ISSUE TITLE
How to make the dropdown animate?

### ISSUE THREAD

**Issue by Ab-Appletic** [jaredrummler/Material-Spinner#17]
So this is cool an all :+1: , but I was wondering if it was possible to animate the spinner, like when the user clicks on it, the ripple shows up. And when the dropdown comes down, it does so with an animation. Is this possible? Your gif shows it is, but yet it doesn't work :(

**Comment by jaredrummler** [comment]
The PopupWindow animation was introduced in Android 6.0. I won't be adding any animation for pre-M.
