### ISSUE TITLE
Tint color

### ISSUE THREAD

**Issue by dbreskvar** [jaredrummler/Material-Spinner#3]
I know this may not be an issue but more like a suggestion.
I have this orange background when I click on the item selected. Does anyone maybe know why? Could I change this to some ripple effect with custom color?

Thanks.

**Comment by jaredrummler** [comment]
Could you please provide some more information? What Android version? Can you please post your XML? Have you changed the background for the spinner? By default, a ripple drawable is used on Android 5.0+.

**Comment by dbreskvar** [comment]
I imported the NiceSpinner directly and made some configurations in code to change the background color, but I used the standard xml format and only changed the ms:background_color or something like that. The color was set to @color/green and not any drawable so I could not find what was causing the orange background. I still have the same problem when clicking on the calendar items, so I guess the problem is not in the library itself, but I do suggest you add some sort of setTintColor or something like that, to override the background color on click?
I was testing on Nexus 10 which has Android version 5.1.2 I think.

**Comment by jaredrummler** [comment]
[`spinner.setBackgroundColor(int)`](https://github.com/jaredrummler/Material-Spinner/blob/b62f4313cbfb3925620c2dfdeea09b536e3fb4d9/lib-materialspinner/src/main/java/com/jaredrummler/materialspinner/MaterialSpinner.java#L221-240) does what you are looking for.
