### ISSUE TITLE
Dropdown arrow incorrect render on rotation

### ISSUE THREAD

**Issue by vbn92** [jaredrummler/Material-Spinner#7]
<img width="317" alt="fine" src="https://cloud.githubusercontent.com/assets/16047613/14538716/ba1868f4-029a-11e6-8974-55baf4d49d19.png">
The dropdown arrow turns weird when you rotate the screen, and becomes fine on click again. 
<img width="476" alt="blur" src="https://cloud.githubusercontent.com/assets/16047613/14538727/c1330e3c-029a-11e6-8e7e-f44d1d35fd26.png">

**Comment by jaredrummler** [comment]
I noticed this behavior in support-v4 23.2.0 and 23.2.1. It should have been fixed with bd97ab11c9102a6ad5c4eaad5d8ed796a674ef0f (see #5). Are you using the latest version (`'com.jaredrummler:material-spinner:1.0.6'`)?

**Comment by vbn92** [comment]
Yes that worked. Thanks!
