### ISSUE TITLE
[Feature Request] Spinner Hint

### ISSUE THREAD

**Issue by TurKurT656** [jaredrummler/Material-Spinner#9]
Hi bro.
this is an awesome lib. can u add hint feature to spinner?
sometimes its better than the default selection

**Comment by jaredrummler** [comment]
Will you please explain your feature request in more detail?

**Comment by TurKurT656** [comment]
its like EditText's Hint. so that the user know what he must select from the spinner.

**Comment by jaredrummler** [comment]
Sorry, but I won't be adding this to the library. You should be able to easily add a TextView above or below the Spinner and change the text based on the selected item.

**Comment by pcegarra** [comment]
This library need a default hint value non selectable...
